# install mysql

- name: install mysql-server
  sudo: yes
  yum:
    name: "{{ item }}"
    state: present
    disable_gpg_check: True 
  with_items:
    - mysql-server
    - mysql-devel
    - MySQL-python
  tags:
    - mysql

- name: start mysqld
  sudo: yes
  service:
    name: mysqld
    enabled: yes
    state: started
  tags:
    - mysql

#@todo when production, create only production database.
- name: create application's mysql database
  mysql_db:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ application_name }}_development"
    - "{{ application_name }}_test"
    - "{{ application_name }}_production"
  tags:
    - mysql
    - create-mysql-database

#@todo delete anonymous user. change root password.
