# basic tasks
#
# selinux がdisableになっていない場合、全てのセットアップ前にansible用にlibselinux-python が必要。
# If selinux is not disabled, require libselinux-python before every setup.
- name: install libselinux-python
  sudo: yes
  yum:
    name: libselinux-python
  tags:
    - basic

# install common tools.
- name: install common tools
  sudo: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - ntp
    - wget
    - expect
    - vim
    - bind-utils
    - traceroute
    - mlocate
    - nkf
    - policycoreutils-python
  tags:
    - basic
    - install-common-tools

- name: locate updatedb
  sudo: yes
  command: updatedb
  changed_when: False
  tags:
    - basic

- name: run ntp 
  sudo: yes
  service:
    name: ntpd
    state: running
    enabled: yes
  tags:
    - basic
    - ntp

